# -*- coding: utf-8 -*-
"""data_clean.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qaJPkRd8yQ5kiY3X1qF7LkZu55PL0921
"""

import re
import pandas as pd

path_to_csv = "https://raw.githubusercontent.com/viviankoko/mnd_crawler/refs/heads/main/mnd_pla.csv"

raw_data = pd.read_csv(path_to_csv)

raw_data



n_airplanes = []
n_warships = []
n_aidz_airplanes = []


for content in raw_data["公告內容"]:
    # Extract 共機架次
    xs_airplanes = re.findall(r"共機(\d+)", content)
    if len(xs_airplanes) > 0:
        n_airplanes.append(int(xs_airplanes[0]))
    else:
        n_airplanes.append(0)

    # Extract 共艦架次
    xs_warships = re.findall(r"共艦(\d+)", content)
    if len(xs_warships) > 0:
        n_warships.append(int(xs_warships[0]))
    else:
        n_warships.append(0)

    # Extract 進入AIDZ共機架次
    xs_aidz_combined = re.findall(r"(?:空域計|空域)(\d+)", content) # 包含 "空域計" 以及 "空域"兩種表達方式
    if len(xs_aidz_combined) > 0:
            n_aidz_airplanes.append(int(xs_aidz_combined[0]))
    else:
        n_aidz_airplanes.append(0)

# 建立整理後的DataFrame，包含日期、共機架次、共艦架次、進入AIDZ共機架次
wrangled_data = pd.DataFrame({
    "日期" : raw_data["日期"],
    "共機架次" : n_airplanes,
    "共艦架次" : n_warships,
    "進入AIDZ共機架次" :n_aidz_airplanes
})

# 顯示整理後的資料
display(wrangled_data)

output_csv_filename = "mnd_pla_wrangled.csv"
wrangled_data = wrangled_data.sort_values("日期", ascending=False).reset_index(drop=True)
wrangled_data.to_csv(output_csv_filename, index=False, encoding="utf-8-sig")



